version: '3'
services:
    web:
        image: nginx:alpine
        container_name: web
        depends_on:
            - app
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

    app:
        build: .
        image: fcgiwrap
        container_name: app
        volumes:
            - ./app:/app
            - ../../bin/nitrogen:/usr/local/bin/nitrogen
            - ../../nitrogen:/nitrogen
        environment:
            NITROGEN_MODULES: /nitrogen
